"""The lxml helpers the walker uses (walker-1).

Generated by expirements/parser-fidelity/port_walker.py from the frozen pf_classes.py
and pf_space.py (616721a): edit the script, never this file. Only what W0-W16 use is
here: parsing, ``body_of``, the hidden-content test, visible text, own rows and cells,
the data-table test, the bare page-number pattern, and ``primary_space``, which the
data-table test uses.
"""

from __future__ import annotations

import re
import unicodedata

import lxml.html
from lxml.html import HtmlElement


def primary_space(s: str) -> str:
    """m(s): NFKC, then delete whitespace (``str.isspace``) and format characters (Cf)."""
    return "".join(
        ch
        for ch in unicodedata.normalize("NFKC", s)
        if not ch.isspace() and unicodedata.category(ch) != "Cf"
    )


HIDDEN_TAGS = frozenset({"script", "style", "head", "title", "noscript", "template"})


_DISPLAY_NONE = re.compile(r"display\s*:\s*none", re.IGNORECASE)


BARE_PAGE_NUMBER = re.compile(
    r"(?:page\s*)?[-\u2013\u2014\s]*\d{1,4}[-\u2013\u2014\s]*", re.IGNORECASE
)


def parse_document(text: str) -> HtmlElement:
    """Parse decoded text with libxml2's HTML parser; the explicit encoding overrides declarations."""
    parser = lxml.html.HTMLParser(encoding="utf-8")
    return lxml.html.document_fromstring(text.encode("utf-8"), parser=parser)


def body_of(root: HtmlElement) -> HtmlElement:
    body = root.find("body")
    return body if body is not None else root


def is_hidden(el: HtmlElement) -> bool:
    """Comments, processing instructions, hidden tags, and inline ``display: none``."""
    if not isinstance(el.tag, str):
        return True
    return el.tag.lower() in HIDDEN_TAGS or bool(
        _DISPLAY_NONE.search(el.get("style") or "")
    )


def visible_text(el: HtmlElement, *, skip_tables: bool = False) -> str:
    """Visible text of ``el``; with ``skip_tables``, text of nested tables is left out."""
    parts: list[str] = []
    stack: list[HtmlElement | str] = [el]
    while stack:
        item = stack.pop()
        if isinstance(item, str):
            parts.append(item)
            continue
        if is_hidden(item) or (skip_tables and item is not el and item.tag == "table"):
            continue
        pending: list[HtmlElement | str] = [item.text] if item.text else []
        for child in item:
            pending.append(child)
            if child.tail:
                pending.append(child.tail)
        stack.extend(reversed(pending))
    return "".join(parts)


def _nearest(el: HtmlElement, tag: str) -> HtmlElement | None:
    parent = el.getparent()
    while parent is not None and parent.tag != tag:
        parent = parent.getparent()
    return parent


def own_rows(table: HtmlElement) -> list[HtmlElement]:
    """The table's own visible rows, not those of nested tables."""
    return [
        tr
        for tr in table.iter("tr")
        if _nearest(tr, "table") is table and not is_hidden(tr)
    ]


def own_cells(row: HtmlElement) -> list[HtmlElement]:
    return [
        cell
        for cell in row.iter("td", "th")
        if _nearest(cell, "tr") is row and not is_hidden(cell)
    ]


def cell_text(cell: HtmlElement) -> str:
    return visible_text(cell, skip_tables=True)


def is_data_table(table: HtmlElement) -> bool:
    """At least two rows with text and one row with two or more non-empty cells (own rows and cells)."""
    rows_with_text = 0
    has_multi_cell_row = False
    for row in own_rows(table):
        filled = sum(1 for cell in own_cells(row) if primary_space(cell_text(cell)))
        rows_with_text += filled > 0
        has_multi_cell_row = has_multi_cell_row or filled >= 2
    return rows_with_text >= 2 and has_multi_cell_row
