"""Public analytical contracts; importing performs no I/O."""

from .completion import document_completions
from .consume import analysis_provenance_hash, reverify_analysis_inputs
from .coverage import build_coverage
from .prevalence import build_analysis, prevalence
from .problems import ANALYSIS_REASONS, AnalysisError
from .records import (
    TABLE_FOREIGN_KEYS,
    TABLE_GRAINS,
    TABLE_MODELS,
    TABLE_SCHEMAS,
    AcquisitionStatus,
    AnalysisInputs,
    AnalysisPart,
    AnalysisPolicy,
    AnalysisRun,
    AnalysisRunRecord,
    AnalysisTables,
    BoundAnalysis,
    CanonicalSnapshot,
    CaptureObservation,
    ClaimAudit,
    ClaimEvidence,
    ClassificationAudit,
    CopyAssertion,
    CopyRow,
    CoverageRow,
    DecisionAudit,
    DocumentCompletion,
    DocumentMetadata,
    EvidenceView,
    EvidenceViewReference,
    ExpectedEvent,
    FixtureAuthorization,
    NoThemeDeclaration,
    Observation,
    PrevalenceRow,
    QuoteAudit,
    RawCacheInputs,
    RawCacheVerification,
    RawSnapshot,
    RejectionAudit,
    StoredAnalysisRun,
    ThemeFamilyMap,
    family_map_hash,
    validate_analysis_tables,
)
from .rows import build_observations

__all__ = [
    "ANALYSIS_REASONS",
    "TABLE_FOREIGN_KEYS",
    "TABLE_GRAINS",
    "TABLE_MODELS",
    "TABLE_SCHEMAS",
    "AcquisitionStatus",
    "AnalysisError",
    "AnalysisInputs",
    "AnalysisPart",
    "AnalysisPolicy",
    "AnalysisRun",
    "AnalysisRunRecord",
    "AnalysisTables",
    "BoundAnalysis",
    "CanonicalSnapshot",
    "CaptureObservation",
    "ClaimAudit",
    "ClaimEvidence",
    "ClassificationAudit",
    "CopyAssertion",
    "CopyRow",
    "CoverageRow",
    "DecisionAudit",
    "DocumentCompletion",
    "DocumentMetadata",
    "EvidenceView",
    "EvidenceViewReference",
    "ExpectedEvent",
    "FixtureAuthorization",
    "NoThemeDeclaration",
    "Observation",
    "PrevalenceRow",
    "QuoteAudit",
    "RawCacheInputs",
    "RawCacheVerification",
    "RawSnapshot",
    "RejectionAudit",
    "StoredAnalysisRun",
    "ThemeFamilyMap",
    "analysis_provenance_hash",
    "build_analysis",
    "build_coverage",
    "build_observations",
    "document_completions",
    "family_map_hash",
    "prevalence",
    "reverify_analysis_inputs",
    "validate_analysis_tables",
]
