"""Freeze the files that shape candidate dumps (spec: Candidate harness > Freeze).

    uv run --locked --all-packages python expirements/parser-fidelity/freeze.py record
    uv run --locked --all-packages python expirements/parser-fidelity/freeze.py verify
    uv run --locked --all-packages python expirements/parser-fidelity/freeze.py amend FILE --reason crash --note "..."

``record`` writes FROZEN.toml with the sha256 of every frozen file; the files must be
committed first, and FROZEN.toml is committed before any candidate runs on a fixture.
After the freeze a frozen file may change only to fix a crash or a network-guard trip
caused by harness code; ``amend`` records such a change, and ``verify`` fails on any
change that is not recorded. A change may never alter a type mapping or a walker rule.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import subprocess
import sys
from pathlib import Path

import tomllib
from pf_paths import HARNESS, REPO_ROOT
from pf_toml import Bare, toml_value

FROZEN_FILES = (
    "adapter_edgartools.py",
    "adapter_edgartools.py.lock",
    "adapter_secparser.py",
    "adapter_secparser.py.lock",
    "control.py",
    "control.py.lock",
    "walker.py",
    "walker.py.lock",
    "pf_classes.py",
    "pf_decode.py",
    "pf_dump.py",
    "pf_paths.py",
    "pf_space.py",
)
FREEZE_FILE = HARNESS / "FROZEN.toml"
ALLOWED_REASONS = ("crash", "network-guard")


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load(freeze_file: Path) -> dict:
    return tomllib.loads(freeze_file.read_text(encoding="utf-8"))


def expected_hashes(freeze: dict) -> dict[str, str]:
    expected = dict(freeze["files"])
    for change in freeze.get("changes", []):
        expected[change["file"]] = change["sha256"]
    return expected


def render(freeze: dict) -> str:
    lines = [
        "# Frozen before the first candidate run on any fixture. Generated by freeze.py; do not edit.",
        f"frozen_on = {toml_value(Bare(str(freeze['frozen_on'])))}",
        f"commit = {toml_value(freeze['commit'])}",
        "",
        "[files]",
    ]
    lines += [
        f"{toml_value(name)} = {toml_value(sha)}"
        for name, sha in freeze["files"].items()
    ]
    for change in freeze.get("changes", []):
        lines += ["", "[[changes]]"]
        lines += [
            f"{key} = {toml_value(Bare(str(change[key])) if key == 'date' else change[key])}"
            for key in ("file", "reason", "previous_sha256", "sha256", "date", "note")
        ]
    return "\n".join(lines) + "\n"


def record(harness: Path, freeze_file: Path, commit: str, today: dt.date) -> dict:
    if freeze_file.exists():
        raise FileExistsError(
            f"{freeze_file} exists; use amend for a permitted post-freeze change"
        )
    freeze = {
        "frozen_on": today,
        "commit": commit,
        "files": {name: sha256_of(harness / name) for name in FROZEN_FILES},
    }
    freeze_file.write_text(render(freeze), encoding="utf-8")
    return freeze


def verify(harness: Path, freeze_file: Path) -> list[str]:
    if not freeze_file.exists():
        return [
            f"{freeze_file.name} is missing: run `freeze.py record` before any fixture run"
        ]
    expected = expected_hashes(load(freeze_file))
    return [
        f"{name} changed after the freeze without a recorded crash or network-guard fix"
        for name, sha in expected.items()
        if sha256_of(harness / name) != sha
    ]


def amend(
    harness: Path, freeze_file: Path, name: str, reason: str, note: str, today: dt.date
) -> dict:
    if reason not in ALLOWED_REASONS:
        raise ValueError(
            f"reason must be one of {ALLOWED_REASONS}; type mappings and walker rules never change"
        )
    freeze = load(freeze_file)
    previous = expected_hashes(freeze)[name]
    current = sha256_of(harness / name)
    if current == previous:
        raise ValueError(f"{name} is unchanged; nothing to amend")
    change = {
        "file": name,
        "reason": reason,
        "previous_sha256": previous,
        "sha256": current,
        "date": today,
        "note": note,
    }
    freeze.setdefault("changes", []).append(change)
    freeze_file.write_text(render(freeze), encoding="utf-8")
    return freeze


def _git(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args], cwd=REPO_ROOT, capture_output=True, text=True, check=False
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("record")
    sub.add_parser("verify")
    fix = sub.add_parser("amend")
    fix.add_argument("file", choices=FROZEN_FILES)
    fix.add_argument("--reason", required=True, choices=ALLOWED_REASONS)
    fix.add_argument("--note", required=True)
    args = parser.parse_args(argv)
    today = dt.datetime.now(dt.UTC).date()

    if args.command == "verify":
        problems = verify(HARNESS, FREEZE_FILE)
        print("\n".join(problems) or "freeze verified")
        return 1 if problems else 0
    paths = [str((HARNESS / name).relative_to(REPO_ROOT)) for name in FROZEN_FILES]
    if (
        _git("diff", "--quiet", "HEAD", "--", *paths).returncode != 0
        or _git("ls-files", "--error-unmatch", *paths).returncode != 0
    ):
        print(
            "commit every frozen file first; the freeze must name a commit that contains them",
            file=sys.stderr,
        )
        return 1
    if args.command == "record":
        commit = _git("rev-parse", "HEAD").stdout.strip()
        record(HARNESS, FREEZE_FILE, commit, today)
        print(
            f"froze {len(FROZEN_FILES)} files at {commit}; commit {FREEZE_FILE.name} now"
        )
        return 0
    amend(HARNESS, FREEZE_FILE, args.file, args.reason, args.note, today)
    print(
        f"recorded a post-freeze {args.reason} fix to {args.file}; commit it with {FREEZE_FILE.name}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
