"""layout-1's pre-registered targets: each targeted class's gold units (plan 5, PB-12).

    uv run --locked --all-packages python expirements/parser-fidelity/layout1_units.py

Writes layout1-units.toml from the gold and the frozen walker's output, never from a
browser capture, so the units are fixed before any capture exists. The classes are
the Stage 3 spec's three targeted residual classes:

1. ``styled_headings``: gold headings the frozen walker found and typed ``paragraph``
   (V2's 23);
2. ``prose_in_tables``: gold text blocks the frozen walker found inside a data table
   (V2's 49 merged blocks, less the 11 tables they merged with);
3. ``stylesheet_hidden``: content a stylesheet hides. The script refuses a fixture
   with a ``<style>`` element or a stylesheet link, since this plan pre-registers no
   definition for one; the eight fixtures have none, so the class is empty.
"""

from __future__ import annotations

from dataclasses import dataclass
from html.parser import HTMLParser

import tomllib
import walker as frozen
from pf_decode import decode_html_bytes
from pf_paths import FIXTURES, HARNESS, MANIFEST
from pf_toml import toml_value
from score import CandidateText, match_block, scored_blocks
from validate_gold import TEXT_TYPES, SourceText, load_gold

UNITS = HARNESS / "layout1-units.toml"
CLASSES = ("styled_headings", "prose_in_tables", "stylesheet_hidden")
HEADER = (
    "# layout-1's pre-registered targets (plan 5, PB-12). Generated by"
    " layout1_units.py; do not edit."
)


@dataclass(frozen=True)
class Unit:
    klass: str
    fixture: str
    block: str
    type: str


class _Stylesheets(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.count = 0

    def handle_starttag(self, tag: str, attrs: list) -> None:
        rel = (dict(attrs).get("rel") or "").lower().split()
        if tag == "style" or (tag == "link" and "stylesheet" in rel):
            self.count += 1


def stylesheets(text: str) -> int:
    """``<style>`` elements and stylesheet links in a decoded source."""
    parser = _Stylesheets()
    parser.feed(text)
    parser.close()
    return parser.count


def fixture_units(fixture: str, raw: bytes, gold: dict) -> list[Unit]:
    """One fixture's units of classes 1 and 2, in gold order."""
    text = decode_html_bytes(raw).text
    if stylesheets(text):
        raise SystemExit(
            f"{fixture} carries a stylesheet, and class 3 has no pre-registered"
            " definition for one: stop and report"
        )
    elements = frozen.parse(text)
    candidate, source = CandidateText(elements), SourceText(raw)
    units = []
    for block in scored_blocks(gold):
        result = match_block(block, candidate, source)
        if not result.found:
            continue
        if (
            result.kind == "heading"
            and elements[result.start.position[0]].type == "paragraph"
        ):
            units.append(Unit(CLASSES[0], fixture, result.id, result.kind))
        if result.kind in TEXT_TYPES and any(
            elements[index].type == "table" for index in result.elements
        ):
            units.append(Unit(CLASSES[1], fixture, result.id, result.kind))
    return units


def derive() -> list[Unit]:
    """Every fixture's units, by class, then fixture, then gold order."""
    manifest = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    units = []
    for entry in sorted(manifest["fixtures"], key=lambda e: e["fixture_id"]):
        directory = FIXTURES / entry["fixture_id"]
        raw = (directory / "source.html").read_bytes()
        units += fixture_units(entry["fixture_id"], raw, load_gold(directory))
    return sorted(units, key=lambda unit: CLASSES.index(unit.klass))


def render(units: list[Unit]) -> str:
    lines = [
        HEADER,
        "# From the gold and the frozen walker's output, never from a browser capture.",
        "",
        "[counts]",
    ]
    lines += [f"{name} = {sum(u.klass == name for u in units)}" for name in CLASSES]
    for unit in units:
        lines += [
            "",
            "[[units]]",
            f"class = {toml_value(unit.klass)}",
            f"fixture = {toml_value(unit.fixture)}",
            f"block = {toml_value(unit.block)}",
            f"type = {toml_value(unit.type)}",
        ]
    return "\n".join(lines) + "\n"


def load_units() -> list[Unit]:
    """The committed units."""
    data = tomllib.loads(UNITS.read_text(encoding="utf-8"))
    return [
        Unit(entry["class"], entry["fixture"], entry["block"], entry["type"])
        for entry in data["units"]
    ]


def main() -> int:
    UNITS.write_text(render(derive()), encoding="utf-8", newline="\n")
    print(f"wrote {UNITS.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
