"""Port the frozen walker into earnings_ingestion.canonical (Stage 3, plan A).

    uv run --locked --all-packages python expirements/parser-fidelity/port_walker.py

walker-1's decoding rule, lxml helpers, and walker are the frozen Stage 1 code. This
script copies the definitions they use, verbatim, from the files FROZEN.toml pins, and
refuses to run if any of them differs from its recorded hash. WALKER_EDITS are the only
changes, and both leave the walker's output unchanged:

- the traversal runs on an explicit stack: each recursive call becomes a ``yield``,
  which ``drive`` runs, so the recursion limit is never raised;
- each W5 ``<pre>`` piece keeps its lines as they were before W4 collapsed them, for
  compensation rule C1.

test_port_equality.py checks that the committed modules are exactly this script's
output, and that they behave as the frozen code does.
"""

from __future__ import annotations

import ast

from freeze import FREEZE_FILE, expected_hashes, load, sha256_of
from pf_paths import HARNESS, REPO_ROOT

TARGET = (
    REPO_ROOT / "packages" / "earnings-ingestion" / "src" / "earnings_ingestion"
) / "canonical"

DECODE_HEADER = '''"""Browser-equivalent decoding of saved release bytes (walker-1).

Generated by expirements/parser-fidelity/port_walker.py from the frozen pf_decode.py
(616721a): edit the script, never this file. The rule: a byte-order mark; a ``<meta>``
charset in the first 1024 bytes, with the WHATWG mappings of the windows-1252 and UTF-8
labels; UTF-8 when the bytes are valid UTF-8; windows-1252 otherwise. Decoding never
fails.
"""

from __future__ import annotations

import codecs
import re
from dataclasses import dataclass

'''

DOM_HEADER = '''"""The lxml helpers the walker uses (walker-1).

Generated by expirements/parser-fidelity/port_walker.py from the frozen pf_classes.py
and pf_space.py (616721a): edit the script, never this file. Only what W0-W16 use is
here: parsing, ``body_of``, the hidden-content test, visible text, own rows and cells,
the data-table test, the bare page-number pattern, and ``primary_space``, which the
data-table test uses.
"""

from __future__ import annotations

import re
import unicodedata

import lxml.html
from lxml.html import HtmlElement


'''

WALKER_HEADER = '''"""The bespoke walker, W0-W16 of expirements/parser-fidelity/walker-rules.md (walker-1).

Generated by expirements/parser-fidelity/port_walker.py from the frozen walker.py and
pf_dump.py (616721a): edit the script, never this file. Two changes, which the
harness's port-equality test shows leave the output unchanged:

- the traversal runs on an explicit stack (``drive``): each recursive call of the
  frozen walker is a ``yield`` here, so no nesting depth reaches the interpreter's
  recursion limit, and the limit is never raised;
- each W5 ``<pre>`` piece keeps its lines as they were before W4 collapsed them, in
  ``Walker.pre_lines``, for compensation rule C1.
"""

from __future__ import annotations

import re
from collections.abc import Generator, Sequence
from dataclasses import dataclass
from typing import Any

from lxml.html import HtmlElement

from earnings_ingestion.canonical.dom import (
    BARE_PAGE_NUMBER,
    body_of,
    is_data_table,
    is_hidden,
    own_cells,
    own_rows,
    parse_document,
    visible_text,
)


'''

WALKER_FOOTER = '''

Walk = Generator[Any, Any, Any]
"""One step of the traversal: it yields a sub-traversal and is sent its result."""


def drive(traversal: Walk) -> Any:
    """Run a traversal on an explicit stack instead of the interpreter's.

    Each yielded sub-traversal runs to completion before its caller resumes, and its
    return value is sent back, exactly as a recursive call would return it. Depth is
    bounded by memory, not by the recursion limit, and no global state changes.
    """
    stack = [traversal]
    result: Any = None
    while stack:
        try:
            call = stack[-1].send(result)
        except StopIteration as done:
            stack.pop()
            result = done.value
        else:
            stack.append(call)
            result = None
    return result


def walk(html: str) -> tuple[list[Element], dict[int, tuple[str, ...]]]:
    """W0-W16 over decoded text: the elements, and each ``<pre>`` piece's lines by index."""
    walker = Walker()
    drive(walker.walk_block(body_of(parse_document(html)), Style(), "block"))
    return walker.elements, walker.pre_lines
'''

DECODE_DEFINITIONS = [
    "PRESCAN_BYTES",
    "_META_CHARSET",
    "_WINDOWS_1252_LABELS",
    "_UTF8_LABELS",
    "_BOMS",
    "_CP1252_UNDEFINED",
    "_LATIN1_TO_WINDOWS_1252",
    "DecodedHtml",
    "decode_html_bytes",
    "decode_windows_1252",
    "_decode_label",
]
SPACE_DEFINITIONS = ["primary_space"]
CLASSES_DEFINITIONS = [
    "HIDDEN_TAGS",
    "_DISPLAY_NONE",
    "BARE_PAGE_NUMBER",
    "parse_document",
    "body_of",
    "is_hidden",
    "visible_text",
    "_nearest",
    "own_rows",
    "own_cells",
    "cell_text",
    "is_data_table",
]
DUMP_DEFINITIONS = ["Cell", "Row", "Element", "grid_text"]
WALKER_DEFINITIONS = [
    "BLOCK_TAGS",
    "HEADING_TAGS",
    "MAX_HEADING_WORDS",
    "MAX_MARKER_CHARS",
    "BULLETS",
    "_BULLET_START",
    "_FOOTNOTE_MARKER",
    "_FOOTNOTE_START",
    "_FOOTNOTE_CELL",
    "_LIST_CELL",
    "_NUMERIC_CELL",
    "_YEAR",
    "_FONT_WEIGHT",
    "_DECORATION",
    "_SYMBOL_FONT",
    "_WHITESPACE",
    "_BLANK_LINE",
    "Style",
    "Run",
    "BREAK",
    "child_style",
    "cell_style",
    "collapse",
    "Walker",
    "classify",
    "styled_runs",
    "slice_runs",
    "marker_row",
    "data_grid",
    "_in_thead",
    "_span",
]

WALKER_EDITS = [
    (
        "        self.lists: list[int] = []  # indices of the open ul/ol containers (W7)\n",
        (
            "        self.lists: list[int] = []  # indices of the open ul/ol containers (W7)\n"
            "        self.pre_lines: dict[int, tuple[str, ...]] = {}  # W5 pieces, for C1\n"
        ),
    ),
    (
        (
            "    def walk_block(self, el: HtmlElement, style: Style, kind: str) -> None:\n"
            "        runs: list[Run] = []\n"
            "        self.walk_content(el, style, runs, kind)\n"
        ),
        (
            "    def walk_block(self, el: HtmlElement, style: Style, kind: str) -> Walk:\n"
            "        runs: list[Run] = []\n"
            "        yield self.walk_content(el, style, runs, kind)\n"
        ),
    ),
    (
        (
            "        self, el: HtmlElement, style: Style, runs: list[Run], kind: str\n"
            "    ) -> None:\n"
        ),
        (
            "        self, el: HtmlElement, style: Style, runs: list[Run], kind: str\n"
            "    ) -> Walk:\n"
        ),
    ),
    (
        "            self.walk_node(child, style, runs, kind, el.tag)\n",
        "            yield self.walk_node(child, style, runs, kind, el.tag)\n",
    ),
    (
        (
            "        self, el: HtmlElement, style: Style, runs: list[Run], kind: str, owner: str\n"
            "    ) -> None:\n"
        ),
        (
            "        self, el: HtmlElement, style: Style, runs: list[Run], kind: str, owner: str\n"
            "    ) -> Walk:\n"
        ),
    ),
    (
        (
            "            self.walk_block_element(el, child_style(el, style), kind)\n"
            "        else:\n"
            "            self.walk_content(el, child_style(el, style), runs, kind)\n"
        ),
        (
            "            yield self.walk_block_element(el, child_style(el, style), kind)\n"
            "        else:\n"
            "            yield self.walk_content(el, child_style(el, style), runs, kind)\n"
        ),
    ),
    (
        "    def walk_block_element(self, el: HtmlElement, style: Style, kind: str) -> None:\n",
        "    def walk_block_element(self, el: HtmlElement, style: Style, kind: str) -> Walk:\n",
    ),
    (
        (
            '            self.walk_block(el, style, f"heading{HEADING_TAGS[tag]}")\n'
            '        elif tag in ("ul", "ol"):\n'
            "            self.walk_list(el, style)\n"
            '        elif tag == "li":\n'
            '            self.walk_block(el, style, "list_item")\n'
            '        elif tag == "table":\n'
            "            self.walk_table(el, style)\n"
        ),
        (
            '            yield self.walk_block(el, style, f"heading{HEADING_TAGS[tag]}")\n'
            '        elif tag in ("ul", "ol"):\n'
            "            yield self.walk_list(el, style)\n"
            '        elif tag == "li":\n'
            '            yield self.walk_block(el, style, "list_item")\n'
            '        elif tag == "table":\n'
            "            yield self.walk_table(el, style)\n"
        ),
    ),
    (
        '        elif tag != "hr":\n            self.walk_block(el, style, kind)\n',
        '        elif tag != "hr":\n            yield self.walk_block(el, style, kind)\n',
    ),
    (
        "    def walk_list(self, el: HtmlElement, style: Style) -> None:\n",
        "    def walk_list(self, el: HtmlElement, style: Style) -> Walk:\n",
    ),
    (
        '        self.walk_block(el, style, "block")\n        self.lists.pop()\n',
        '        yield self.walk_block(el, style, "block")\n        self.lists.pop()\n',
    ),
    (
        "        runs = styled_runs(el, style)\n",
        "        runs = drive(styled_runs(el, style))\n",
    ),
    (
        (
            "        for start, end in zip(starts, ends, strict=True):\n"
            '            self.flush(slice_runs(runs, start, end), "block", "pre")\n'
        ),
        (
            "        for start, end in zip(starts, ends, strict=True):\n"
            "            piece = slice_runs(runs, start, end)\n"
            "            emitted = len(self.elements)\n"
            '            self.flush(piece, "block", "pre")\n'
            "            if len(self.elements) > emitted:  # one block at most: no BREAK in <pre>\n"
            '                lines = "".join(run.text for run in piece).split("\\n")\n'
            "                self.pre_lines[emitted] = tuple(lines)\n"
        ),
    ),
    (
        "    def walk_table(self, table: HtmlElement, style: Style) -> None:\n",
        "    def walk_table(self, table: HtmlElement, style: Style) -> Walk:\n",
    ),
    (
        '            self.walk_block(caption, child_style(caption, style), "block")\n',
        '            yield self.walk_block(caption, child_style(caption, style), "block")\n',
    ),
    (
        '                    self.walk_block(cell, cell_style(table, cell, style), "block")\n',
        '                    yield self.walk_block(cell, cell_style(table, cell, style), "block")\n',
    ),
    (
        "def styled_runs(el: HtmlElement, style: Style) -> list[Run]:\n",
        "def styled_runs(el: HtmlElement, style: Style) -> Walk:\n",
    ),
    (
        "            runs.extend(styled_runs(child, child_style(child, style)))\n",
        "            runs.extend((yield styled_runs(child, child_style(child, style))))\n",
    ),
    (
        "    runs = styled_runs(marker_cell, cell_style(table, marker_cell, style))\n",
        "    runs = drive(styled_runs(marker_cell, cell_style(table, marker_cell, style)))\n",
    ),
]


def frozen_source(name: str) -> str:
    """A frozen harness file's text, refused unless it has its FROZEN.toml hash."""
    path = HARNESS / name
    if sha256_of(path) != expected_hashes(load(FREEZE_FILE))[name]:
        raise ValueError(f"{name} differs from its hash in FROZEN.toml")
    return path.read_text(encoding="utf-8")


def _names(node: ast.stmt) -> list[str]:
    if isinstance(node, ast.FunctionDef | ast.ClassDef):
        return [node.name]
    if isinstance(node, ast.Assign):
        return [target.id for target in node.targets if isinstance(target, ast.Name)]
    return []


def copy_definitions(name: str, wanted: list[str]) -> str:
    """The named top-level definitions of a frozen file, verbatim, in file order.

    Neighbouring definitions are copied as one slice with their original blank lines;
    separate slices are joined by two blank lines, as Ruff lays out top-level code.
    """
    text = frozen_source(name)
    lines = text.splitlines(keepends=True)
    slices: list[list[int]] = []  # [first line, last line], 1-based and inclusive
    found: set[str] = set()
    extends = False
    for node in ast.parse(text).body:
        names = [name for name in _names(node) if name in wanted]
        if not names:
            extends = False
            continue
        decorators = getattr(node, "decorator_list", [])
        first = min([node.lineno, *(decorator.lineno for decorator in decorators)])
        if extends:
            slices[-1][1] = node.end_lineno
        else:
            slices.append([first, node.end_lineno])
        extends = True
        found.update(names)
    missing = sorted(set(wanted) - found)
    if missing:
        raise ValueError(f"{name} defines no {missing}")
    return "\n\n".join("".join(lines[start - 1 : end]) for start, end in slices)


def edit(text: str, old: str, new: str) -> str:
    """Replace the one occurrence of ``old``; anything else is a stale edit."""
    count = text.count(old)
    if count != 1:
        raise ValueError(f"{count} occurrences of {old!r}; expected exactly one")
    return text.replace(old, new)


def build_modules() -> dict[str, str]:
    """The three ported modules' text, by file name; nothing is written."""
    decode = copy_definitions("pf_decode.py", DECODE_DEFINITIONS)
    space = copy_definitions("pf_space.py", SPACE_DEFINITIONS)
    classes = copy_definitions("pf_classes.py", CLASSES_DEFINITIONS)
    shapes = copy_definitions("pf_dump.py", DUMP_DEFINITIONS)
    walker = copy_definitions("walker.py", WALKER_DEFINITIONS)
    for old, new in WALKER_EDITS:
        walker = edit(walker, old, new)
    return {
        "decode.py": DECODE_HEADER + decode,
        "dom.py": DOM_HEADER + space + "\n\n" + classes,
        "walker.py": WALKER_HEADER + shapes + "\n\n" + walker + WALKER_FOOTER,
    }


def main() -> int:
    TARGET.mkdir(parents=True, exist_ok=True)
    for name, text in build_modules().items():
        (TARGET / name).write_text(text, encoding="utf-8")
        print(f"wrote {(TARGET / name).relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
