"""Freeze layout-1 and its comparison before any fixture is captured (plan 5, PB-13).

    uv run --locked --all-packages python expirements/parser-fidelity/preregister.py record
    uv run --locked --all-packages python expirements/parser-fidelity/preregister.py verify
    uv run --locked --all-packages python expirements/parser-fidelity/preregister.py amend PATH --reason crash --note "..."

``record`` writes layout1-preregistered.toml with the SHA-256 of every file that
decides the pre-registered comparison's numbers: the capture adapter, its extractor,
policy, records, and fixture format; layout-1 and the modules it runs; the fallback's
triggers; the units and their loader; the comparison; and the frozen scorer it calls.
The files must be committed first, and the record is committed before
tests/integration/capture_browser_fixtures.py captures any release.

After the freeze a file may change only to fix a crash, or an element set that
``validate_elements`` refuses, on a fixture capture; ``amend`` records such a change,
and ``verify`` fails on any change that is not recorded. A change may never alter a
type decision, a mapping rule, a unit, or a metric, and every amendment makes the
comparison's numbers post-hoc, which the verification record says.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import subprocess
import sys
from pathlib import Path

import tomllib
from pf_paths import HARNESS, REPO_ROOT
from pf_toml import Bare, toml_value

_SOURCE = "packages/earnings-ingestion/src/earnings_ingestion"
_HARNESS = "expirements/parser-fidelity"
PREREGISTERED_FILES = (
    f"{_SOURCE}/browser/metadata.py",
    f"{_SOURCE}/browser/policy.py",
    f"{_SOURCE}/browser/records.py",
    f"{_SOURCE}/browser/selenium_capture.py",
    f"{_SOURCE}/browser/serialize.py",
    f"{_SOURCE}/canonical/blocks.py",
    f"{_SOURCE}/canonical/compensate.py",
    f"{_SOURCE}/canonical/dom.py",
    f"{_SOURCE}/canonical/normalize.py",
    f"{_SOURCE}/canonical/triggers.py",
    f"{_SOURCE}/canonical/walker.py",
    f"{_SOURCE}/layout/__init__.py",
    f"{_SOURCE}/layout/align.py",
    f"{_SOURCE}/layout/blocks.py",
    f"{_SOURCE}/layout/extract.py",
    f"{_SOURCE}/layout/records.py",
    f"{_HARNESS}/layout1-units.toml",
    f"{_HARNESS}/layout1_report.py",
    f"{_HARNESS}/layout1_units.py",
    f"{_HARNESS}/pf_text.py",
    f"{_HARNESS}/score.py",
    f"{_HARNESS}/validate_gold.py",
    f"{_HARNESS}/walker1_report.py",
)
PREREGISTERED = HARNESS / "layout1-preregistered.toml"
ALLOWED_REASONS = ("crash", "invalid-elements")


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load(record_file: Path) -> dict:
    return tomllib.loads(record_file.read_text(encoding="utf-8"))


def expected_hashes(record: dict) -> dict[str, str]:
    expected = dict(record["files"])
    for change in record.get("changes", []):
        expected[change["file"]] = change["sha256"]
    return expected


def render(record: dict) -> str:
    lines = [
        "# Pre-registered before any release capture. Generated by preregister.py.",
        f"frozen_on = {toml_value(Bare(str(record['frozen_on'])))}",
        f"commit = {toml_value(record['commit'])}",
        "",
        "[files]",
    ]
    lines += [
        f"{toml_value(name)} = {toml_value(sha)}"
        for name, sha in record["files"].items()
    ]
    for change in record.get("changes", []):
        lines += ["", "[[changes]]"]
        lines += [
            f"{key} = {toml_value(Bare(str(change[key])) if key == 'date' else change[key])}"
            for key in ("file", "reason", "previous_sha256", "sha256", "date", "note")
        ]
    return "\n".join(lines) + "\n"


def record(root: Path, record_file: Path, commit: str, today: dt.date) -> dict:
    if record_file.exists():
        raise FileExistsError(
            f"{record_file.name} exists; use amend for a permitted post-freeze fix"
        )
    frozen = {
        "frozen_on": today,
        "commit": commit,
        "files": {name: sha256_of(root / name) for name in PREREGISTERED_FILES},
    }
    record_file.write_text(render(frozen), encoding="utf-8")
    return frozen


def verify(root: Path, record_file: Path) -> list[str]:
    if not record_file.exists():
        return [f"{record_file.name} is missing: run `preregister.py record` first"]
    return [
        f"{name} changed after the pre-registration without a recorded fix"
        for name, sha in expected_hashes(load(record_file)).items()
        if not (root / name).is_file() or sha256_of(root / name) != sha
    ]


def amend(
    root: Path, record_file: Path, name: str, reason: str, note: str, today: dt.date
) -> dict:
    if reason not in ALLOWED_REASONS:
        raise ValueError(
            f"reason must be one of {ALLOWED_REASONS}; type decisions, mapping rules,"
            " units, and metrics never change"
        )
    frozen = load(record_file)
    previous = expected_hashes(frozen)[name]
    current = sha256_of(root / name)
    if current == previous:
        raise ValueError(f"{name} is unchanged; nothing to amend")
    change = {
        "file": name,
        "reason": reason,
        "previous_sha256": previous,
        "sha256": current,
        "date": today,
        "note": note,
    }
    frozen.setdefault("changes", []).append(change)
    record_file.write_text(render(frozen), encoding="utf-8")
    return frozen


def _git(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args], cwd=REPO_ROOT, capture_output=True, text=True, check=False
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("record")
    sub.add_parser("verify")
    fix = sub.add_parser("amend")
    fix.add_argument("file", choices=PREREGISTERED_FILES)
    fix.add_argument("--reason", required=True, choices=ALLOWED_REASONS)
    fix.add_argument("--note", required=True)
    args = parser.parse_args(argv)
    today = dt.datetime.now(dt.UTC).date()

    if args.command == "verify":
        problems = verify(REPO_ROOT, PREREGISTERED)
        print("\n".join(problems) or "pre-registration verified")
        return 1 if problems else 0
    if (
        _git("diff", "--quiet", "HEAD", "--", *PREREGISTERED_FILES).returncode != 0
        or _git("ls-files", "--error-unmatch", *PREREGISTERED_FILES).returncode != 0
    ):
        print(
            "commit every pre-registered file first; the record must name a commit"
            " that contains them",
            file=sys.stderr,
        )
        return 1
    if args.command == "record":
        commit = _git("rev-parse", "HEAD").stdout.strip()
        record(REPO_ROOT, PREREGISTERED, commit, today)
        print(
            f"pre-registered {len(PREREGISTERED_FILES)} files at {commit};"
            f" commit {PREREGISTERED.name} now"
        )
        return 0
    amend(REPO_ROOT, PREREGISTERED, args.file, args.reason, args.note, today)
    print(
        f"recorded a post-freeze {args.reason} fix to {args.file};"
        f" commit it with {PREREGISTERED.name}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
